---
title: Mission Statements
author: Andy
date: '2022-04-26'
slug: []
categories:
  - Tech
tags:
  - Miscellaneous
subtitle: ''
description: ''
image: ''
showtoc: false
---

Sometime over the pandemic I read a book called [Essentialism: The Disciplined Pursuit of Less](https://bookshop.org/books/essentialism-the-disciplined-pursuit-of-less/9780804137409) by Greg McKeown. It was a classic business-ish time management book in which the premise is be more selective in how you spend your time and effort. Like most of these books, the author came across a bit cultish in his zeal for this, and the thesis was hammered via way too much repetitiveness.

That being said, I did resonate with the message, and also enjoyed some of the examples that he wrote about. One of those examples had to do with mission statements. The author points out that a well-crafted mission statement lays outr a strategy that is both concrete and inspirational, and has intent that is meaningful and memorable. This, he posits, reduces decision making later on since all future decisions will need to cohere with the mission.

Most mission statements that I have seen (especially in academia) are inspirational, but too general ans vague to make decisions from. For example, consider the mission statement of our college (CEHD):

> The mission of the University of Minnesota College of Education and Human Development is to contribute to a just and sustainable future through engagement with the local and global communities to enhance human learning and development at all stages of the life span.

Inspirational? Yes. But, this is about as vague as it gets. McKeown argues that one should be able to make hiring decisions based on the mission. How would you differentiate between multiple qualified candidates based on this mission? This is mission statement by committee if I have ever seen it (which is academia in a nutshell).

McKeown writes that in putting together a mission statement, the essentialist would ask: "If we could be truly excellent at only one thing, what would it be?" He also suggests that a second question that needs to be answered is: "How will we know if we have succeeded?" The CEHD mission statement fails to answer both of these questions.

The mission statement for my program, Quantitative Methods in Education, is not much better.

> QME strives to be a premier program recognized for leadership, innovation, and excellence, and to enable human potential through the advancement of education. QME prepares students to become cutting-edge professionals in educational measurement, evaluation, statistics, and statistics education, through excellence in teaching, research, and service; and through investigating and developing research methodology in education.

Reading this, it is unclear what our mission is at all, let alone what  one thing we are aiming to be truly excellent at. When we wrote it, it ended up being so general in order to appease all of the stakeholders in the program. Which academic program doesn't want to be recognized for leadership, innovation, and excellence? Are there programs that want to produce graduates who aren't excellent at teaching, research, and service?

I also have no idea how we will know when we have succeeded. Is it when we are recognized for leadership, innovation, AND excellence? By whom? Is it when we produce "cutting-edge" professionals? When our graduates are recognized for their excellence teaching, research, AND service? Or is it when our students investigate and develop research methodology that enables human potential through the advancement of education? (What does that even mean???)

Worse than all of these is my department's mission statement. The Educational Psychology mission statement is:

> Educational psychology involves the study of cognitive, emotional, and social learning processes that underlie education and human development across the lifespan. Research in educational psychology advances scientific knowledge of those processes and their application in diverse educational and community settings. The department provides training in the psychological foundations of education, research methods, and the practice and science of counseling psychology, school psychology, and special education. Faculty and students provide leadership and consultation to the state, the nation, and the international community in each area of educational psychology. The department's scholarship and teaching enhance professional practice in schools and universities, community mental health agencies, business and industrial organizations, early childhood programs, and government agencies.

This is more of a description of what the faculty and students in our department do; it does not lay out a mission. Even worse, it isn't even very inspirational. 


