baseurl = "https://www.datadreaming.org/"
title = "Andrew Zieffler"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "img/typewriter.png"
  SEOTitle = "Academic. Data lover. Statistics enthusiast."
  description = ""
  keyword = ""
  slogan = "Academic. Data lover. Statistics enthusiast."

  image_404 = "img/404-bg.jpg"
  title_404 = "Whoops!"

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Academic. Data lover. Statistics enthusiast."
  sidebar_avatar = "img/andy.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false
  # reward_guide = "" 

  friends = false
  bookmarks = false
  about_me = false

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/main.css", "css/academicons.min.css"]
  custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js", "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"]

  # Highlight.js theme
  # demo: https://highlightjs.org/static/demo/
  highlightjs = "monokai-sublime"
  highlightjsLang = ["r"]

  [params.social]
  #rss            = true 
  #email          = "zief0002@umn.edu"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/andrewzieffler/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #github         = "https://github.com/zief0002"
  #wechat         = "your wechat qr code image"
  #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Ask Good Questions (Allan Rossman)"
  href =  "https://askgoodquestions.blog/"
  [[params.friend_link]]
  title = "Educate-R (Brandon LeBeau)"
  href =  "https://brandonlebeau.org/"
  [[params.friend_link]]
  title = "Marianne Elmquist"
  href =  "https://marianne-elmquist.me/"
  [[params.friend_link]]
  title = "R Weekly"
  href =  "https://rweekly.org"
  [[params.friend_link]]
  title = "Statistical Journeys (Vimal Rao)"
  href =  "https://statisticaljourneys.home.blog/"
  [[params.friend_link]]
  title = "Statistics Teaching and Learning Corner"
  href =  "https://stattlc.com/"
  [[params.friend_link]]
  title = "Teach Data Science (Hunter Glanz, Jo Hardin, and Nick Horton)"
  href =  "https://teachdatascience.com/"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"
  [[params.addtional_menus]]
  title =  "CONTACT"
  href =  "/top/contact/"
  [[params.addtional_menus]]
  title =  "PUBLICATIONS"
  href =  "/top/publications/"
  [[params.addtional_menus]]
  title =  "TEACHING"
  href =  "/top/teaching/"
  [[params.addtional_menus]]
  title =  "BLOGROLL"
  href =  "/top/blogroll/"
  

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

