---
title: Computing Talk at SSC 2018
author: Andrew Zieffler
date: '2018-06-03'
slug: ssc-computing-talk
categories: []
tags: ["R", "Teaching", "Computing"]
---

I am giving a talk at the [46th Annual Meeting of the Statistical Society of Canada](https://ssc.ca/en/publications/ssc-liaison/vol-32-1-february-2018/ssc-2018-46th-annual-meeting-statistical-society) in Montreal on June 05, 2018. The talk is part of an invited session on *Teaching Statistics to Graduate Students in the Health and Social Sciences*. Information, including the slides, is available below.

**Title:** *Statistical Computing: Non-Ignorable Missingness in the Graduate-Level Social Science Curriculum*

**Abstract:** In 2010, Nolan and Temple Lang pointed out that \"computational literacy and programming are as fundamental to statistical practice and research as mathematics\". Since that time computation has become an even more important skillset for researchers and scientists who use statistics. Many graduate-level statistics programs in the social sciences have yet to adopt statistical computing into the curriculum. Students either learn computing on their own or its teaching is relegated to specialty, often advanced, coursework. In either case, it is often only a small minority of quantitatively-focused students that are exposed to computing. The majority of graduate-level social science students, however, are not quantitatively focused. To what extent should they learn statistical computing? Which aspects of statistical computing should they be exposed to? In this talk, I explore these questions and offer some advice for teaching statistical computing to graduate-level social science students.

**Slides:** Available at https://github.com/zief0002/website/raw/master/public/files/computing-talk-2018-05-07.pdf



