---
title: "CV: Sale Items vs. Research Plan"
author: '~'
date: '2019-05-02'
tags:
- CV
- Quotation
header:
  caption: ''
  image: ''
---

Karen Kelsky writes about the importance of identifying a research plan and building your CV around this plan in her book [The Professor is In: The Essential Guide to Turning Your Ph.D. into a Job](https://www.amazon.com/Professor-Essential-Guide-Turning-Ph-D/dp/0553419420).

> A reader once wrote to explain: During my years as a tenure track assistant professor, I went about publishing and doing research the way I do the grocery shopping: concentrating on the sale items like conferences, book reviews, on-line collaborations, i.e., all things that seemed "affordable." As a result stock up on unnecessary items and find myself too tired to focus on the important things, those items that do not go on sale, but that are the nbuilding block of a good kitchen: articles and books. Although I have managed to publish quite a bit, I have squandered a lot of time and energy, because I did not have a clearly elaborated research plan. (p. 95)

I see this strategy of adding easy line items to the CV with many graduate students and early career professionals. This is not to say that giving talks and writing blog posts are worthless, they aren't. But, as Roger Peng pointed out in [The Effort Report](https://effortreport.libsyn.com/), if you think about your time, which is finite, as a pie chart, anything you do adds a "wedge" into your pie chart and by definition takes away area (time) from something else. If you have time constraints, it is better to optimize the time you spend, and for most academics that means focusing on scholarship, especially articles and books which are often weighted more in tenure and promotion decisions than other elements of scholarship. 

The advice Karen gives is solid; build a research agenda and then spend your time on things that matter. 



<br /><br />
