---
title: "Q&A with Becoming a Teacher of Statistics Class: Part II"
author: "~"
date: 2018-03-30
tags: ["Teaching", "FAQ"]
css: "/css/bracket.css"
---

This post is the second in a series of blogposts in which I respond to questions from the students in the *Becoming a Teacher of Statistics* course. In today's posting I respond to questions related to several of the projects I have worked on over the years.


#### Can you tell us a little about your AIMS project? I think it's not always easy for everyone to apply guidelines in order to change their behavior (in any context), but your AIMS project seems to fill that gap for stats educators-that is, it explicitly creates educational materials aligned with GAISE. Can you also tell us about some of the difficult decision points in developing your materials?

Wow. You are making me think. I honestly haven't thought about AIMS in a long time (I think we started writing these materials in 2005ish). At that time, the [GAISE recommendations](http://www.amstat.org/asa/education/Guidelines-for-Assessment-and-Instruction-in-Statistics-Education-Reports.aspx) had just come out. Joan Garfield, my advisor and colleague, was the chair of the committee that wrote the GAISE college report. She was also the person that had transformed the curriculum in our undergraduate course (EPsy 3264) to what it was at that time.

There were two graduate students, myself and [Sharon Lane-Getaz](https://wp.stolaf.edu/education/sharon/), who were teaching 3264 at that time. We actually would write the curriculum as we went, writing a lesson, teaching it and observing the other teach, and then meeting afterward in Joan's office to re-vise the lesson and write the next one. It was a very invloved process, and, in those early iterations, a little rough. 

One of the major decisions was to choose what topics would be included in the course and which wouldn't. We also really switched the focus from calculation to conceptual understanding. The choice of software was also a decision point. [Bill Finzer](https://concord.org/about/staff/william-finzer/) was one of the project's advsiors because we were pretty convinced that Fathom was the software we wanted to use in the course. (Although, looking back on the actual lessons, I think the materials are pretty software agnostic.)


#### How much biology did you have to know to contribute meaningfully to the development of BioSQuaRE? Or, are you just an expert in assessment creation who applied his expertise to biology?

Thankfully, not much. My high school and undergraduate experiences in biology were only slightly better than those in chemistry (although I did really enjoy an environmental biology course I took). I primarily brought assessment development expertise to the project. The biology expertise (from others on the project) was primarily in ensuring that the items had a context related to biology, as the assessment itself was geared toward measuring students' quantitative skills and knowledge. 


#### What's next for the CATALST project? Is there hope to expand it to other universities or high schools outside Minnesota?

Good question. In thinking about the current CATALST curriculum, we do not have explicit plans to expand to other institutions, but if there is a grass roots expansion, the more the merrier. My sense is that it would be a pretty good curriculum for high schools, but that many high school teachers are not aware of the its existence. (Perhaps we should do a workshop aimed at high school teachers at USCOTS next year...) 

One way that we have thought about "growing" the curriculum is to write a Lab Manual for use with R. [Jim Albert](http://www-math.bgsu.edu/~albert/) taught CATALST with R to his students at Bowling Green when we first started the project many moons ago. I think this could be used as a skeleton for writing such a Lab Manual, but updating the syntax to use **mosaic** and **tidyverse** functions. The one reason we have not done this yet is that I am unsure that R is the correct choice of software in an introductory statistics course for undergraduates. Inference is hard to learn. Inference and coding may be too much at that level.

Lately, there have been a few of us (loosely) thinking about what a CATALST-like course that emphasizes data science might look like. In the early days of CATALST, we had thought about more forward-thinking units such as prediction/classification, and visualization. These were ultimately scrapped, but in today's climate might be good candidates for a data science-driven curriculum. We would keep the pedagogical approach used in the CATALST course (cooperative learning, teacher as guide-on-the-side, discussion) and update the content.


