---
title: "Q&A with Becoming a Teacher of Statistics Class: Part IV"
author: "~"
date: 2018-04-09
tags: ["Teaching", "FAQ"]
---

This post is the fourth (and last) in a series of blogposts in which I respond to questions from the students in the *Becoming a Teacher of Statistics* course. In today's posting I respond to questions that asked me for predictions about the future of statistics teaching and statistics education research.

Before I get into the Q&amp;A, let me just state: Prediction is hard. Leland Wilkinson in [The Future of Statistical Computing](https://www.tandfonline.com/doi/abs/10.1198/004017008000000460) reminded us of this when he cited a prediction about computers that Andrew Hamilton made in a 1949 issue of *Popular Mechanics*

> Where a calculator like the ENIAC today is equipped with 18,000 vacuum tubes and weighs 30 tons, computers in the future may have only 1,000 vacuum tubes and perhaps weigh only $1 \dfrac{1}{2}$ tons.

So, read my responses with caution. 

#### Given your experience of evolution of Statistics Education research over the past around 30 years or so, where do you envision Stat Ed research to be, say in the ensuing 30 years? What major stumble-blocks, if any, might the stat educators face along the path? What should be some best strategies to overcome those?

My hope is that statistics education research will be breaking out of its infancy and statistics educators will be paying more attention to what the research is showing with regards to pedagogy and stduent learning. I also hope that the community of statistics education researchers has, by that time, begun to coalesce around a common research agenda. 

My cynical answer is that we will be in the same place as we are right now, with too few statistics educators aware of the research that exists. 

The reality will probably be somewhere between the two. 

As I consider what challenges the research community faces, I can't help but pause and think about how statistics education has changed over time, even in the last 10 years. Computing has played a major role in this change. This has led to curriculum changes and questions about how to incorporate computing into courses. How do you teach both the statistical and computing content together? How much computing do we teach? Which computing tools do we teach? I forsee these challenges only growing in the future.

When I answered this in the *Becoming a Teacher of Statistics* class, Dennis Pearl asked me whether one issue for the research community is the pace at which technology is driving the pace of change. New computing tools (R packages, dashboards, etc.) are appearing every day. These tools are adopted (and just as quickly abandoned as the new tool comes along) before any research can possibly happen.

Research moves slowly. It is not uncommon for the timeline of research to be two to three years to get a study together, obtain IRB approval, conduct the study, write up the results, and disseminate them to the community. This timeline is not compatible with the pace of technological change.

I don't know what the answer to this is, but my first thought is that companies like Google are doing research in this fast-paced world, so maybe we can learn from what they are doing. My second thought is that companies like Google often have very clear measurements (did a person click on an ad), and statistics education does not (what does it mean to learn computing). 


#### Just like 20 years ago Bayesian Inference was not considered something to be taught in intro stats course (MCMC and computation were still a problem), do you think there is something that is overlooked nowadays that could have a potential to be taught in the future?

Another prediction question. `r emo::ji("weary")` This one is easier. Yes.

Now the follow-up is: Like what? I'm not sure, but inevitably something will rear up. In the 1990's, statistics education began to push toward teaching more conceptual understanding and away from the formulaic and dogged calculation of probability problems. Asa result, probability took on a much smaller role in the curricula developed during this time. Twenty years later, the rise of simulation-based approaches to statistical inference brings probability modeling right back to the forefront, albeit in a different manner than before. 

I still am a bit skeptical about teaching Bayesian inference in an introductory course. The ideas yes; the methods no. While incredibly useful to an applied statistician and scientists, Bayesian calculations are not stright forward nor easy. Computing, of course, can make these quicker, but will students understand what they are doing? Or will it just be following recipes? Now teaching the big ideas behind Bayesian inference make perfect sense in an introductory course; the idea that combining prior beliefs with evidence (data) leads to updated beliefs. This makes a lot of sense to me. Having students reason about how thes posterior beliefs are impacted by the data when those prior beliefs are strong versus when they are weak can lead to great discussion of how we weigh evidence and what that means for drawing conclusion (and also why it is so hard to sway people's opinions). 


#### There are many foreign students coming to America for education purpose in different levels: high school, college and graduate level. Do you think this will influence the curriculum of the courses offered in America?

Probably not. The American education system has an inertia that is very difficult to change. Even oodles of research evidence seems to have very little impact on this system. I have a theory that this may be because adults (i.e., parents) have gone through and experienced the system, and there is a hindsight bias about that experience. "In my day we worked on algebra problems nonstop, so you should too."

You might think that at least colleges and universities would be quicker to change. It turns out that here too the system is slow to change. Individuals have more autonomy to make changes in their clasrooms at this level, but the sytem as a whole seems to be stuck on a fulcrum of "what we used to do". 

In statistics, the reformers have been asking for change in the introductory course for years, citing the changes in the high school curriculum and standards such as Common Core (or previous to that the NCTM mathemateics standards---which have been around since the 1980's), with little result. So, I am not optimistic that an influx of foreign students will have an influence either.


