---
title: Journal of Statistics and Data Science Education (JSE) Reference Examples
author: Andy
date: '2020-09-14'
slug: journal-of-statistics-education-jse-references
categories: []
tags:
  - Writing
  - Statistics Education
subtitle: ''
description: ''
image: ''
showtoc: false
---

This post is to act as more of a reference for myself regarding the referencing for JSE articles. JSE references use the American Statistical Association's style guide which is [here](https://amstat.tfjournals.com/asa-style-guide/). 

Zotero's Style Repository includes a style file [here](https://www.zotero.org/styles/american-statistical-association).


## Article Examples

Gould, R. (2004), "Variability: One Statistician's View," *Statistics Education Research Journal,* 3, 7--16. Available at https://iase-web.org/documents/SERJ/SERJ3(2)_Gould.pdf?1402525005.

&ndash; &ndash; (2017), "Data Literacy is Statistical Literacy," *Statistics Education Research Journal,* 16, 22--25. Available at https://iase-web.org/documents/SERJ/SERJ16(1)_Gould.pdf?1498680916.

Justice, N., Le, L., Sabbag, A., Fry, E., Ziegler, L., and Garfield, J. (2020), "The CATALST Curriculum: A Story of Change," *Journal of Statistics Education,* 28, 175--186, DOI: 10.1080/10691898.2020.1787115. Available at https://www.tandfonline.com/doi/full/10.1080/10691898.2020.1787115.


- If two or more works by the same author or team of authors have the same publication date, **list them by order of appearance in the text** and distinguish them by lowercase "a," "b," and so on, after the date: "(1970a)." 

<br />


## Book Examples

American Statistical Association. (2005), *Guidelines for Assessment and Instruction in Statistics Education: College Report,* Washington, DC: Author. Available at https://www.amstat.org/ASA/Education/Guidelines-for-Assessment-and-Instruction-in-Statistics-Education-Reports.aspx.

Breiman, L., Friedman, J. H., Olshen, R. A., and Stone, C. I. (1984), *Classification and Regression Trees,* Belmont, California: Wadsworth.

Franklin, C., Bargagliotti, A., Case, C., Kader, G., Schaeffer, R., and Spangler, D. (2015), *The Statistical Education of Teachers,* Arlington, VA: American Statistical Association. Available at https://www.amstat.org/asa/files/pdfs/EDU-SET.pdf.


<br />

## Book Chapter/Proceedings Examples

Holcomb, J., Chance, B., Rossman, A., and Cobb, G. (2010), "Assessing Student Learning about Statistical Inference," in *Data and Context in Statistics Education: Towards an Evidence-Based Society. Proceedings of the Eighth International Conference on Teaching Statistics,* ed., C. Reading., Ljubljana, Slovenia. Voorburg, The Netherlands: International Statistical Institute. Available at https://iase-web.org/documents/papers/icots8/ICOTS8_5F1_CHANCE.pdf.

Lesh, R., Hoover, M., Hole, B., Kelly, A., and Post, T. (2000), "Principles for Developing Thought Revealing Activities for Students and Teachers," in *Handbook of Research Design in Mathematics and Science Education,* eds., R. Lesh and A. Kelly, Mahwah, NJ: Lawrence Erlbaum Associates, pp. 591--645.


<br />

## Software Examples

Becker, R. A., Wilks, A. R., Brownrigg, R., Minka, T. P., and Deckmyn, A. (2018), "maps: Draw Geographical Maps," R Package Version 3.3.0. Available at https://CRAN.R-project.org/package=maps.

R Core Team (2020), *R: A Language and Environment for Statistical Computing,* Vienna, Austria: R Foundation for Statistical Computing. Available at https://www.R-project.org.


