---
title: Packages and Resources for Data Viz
author: Andy
date: '2020-12-16'
slug: []
categories:
  - notes
tags:
  - R
  - Teaching
subtitle: ''
description: ''
image: ''
showtoc: false
---

*I have written several notes to myself over the years as reminders. These include ideas for research, R packages I have seen and may use sometime), things to-do, etc.  I am in the process of making some of these notes more public on my blog. This will act as a more searchable, curated "note" for myself, but also makes it available to anyone else who would benefit.*

These are resources I was compiling for use in our course, *EPsy 1261: Understanding Data Stories through Visualization &amp; Computing*.

<br />

## Online Books

- Healy, K. (2018). [Data Visualization: A Practical Introduction](https://socviz.co/).
  + [socviz](https://github.com/kjhealy/socviz): R package to accompany Kieran Healy's book, *Data Visualization: A Practical Introduction*. It includes datasets, functions, and course materials.
- Wilke, C. O. (2019). [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/index.html).
  + [practical_ggplot2](https://github.com/clauswilke/practical_ggplot2): R package to accompany Claus Wilke's book,  *Fundamentals of Data Visualization*. Great suggestions for making plots look great!

<br />


## General Resources (Blog Posts, Slides, etc.)

- Barrett, M. (2019). [Designing ggplots: Making clear figures that communicate.](https://designing-ggplots.netlify.app/) Slides from a workshop presented at Southern California R Users All-Hands Meetup, Burbank, CA.
- Chase, W. (2019, May 29). [R you ready to make charts?](https://www.williamrchase.com/slides/ggplot_intro.html#1) Slides from a Philly Dataviz Meetup.
- Correll, M. (2018, November 20). [What does "visualization literacy" mean, anyway?](https://medium.com/multiple-views-visualization-research-explained/what-does-visualization-literacy-mean-anyway-22f3b3badc0) *Multiple Views: Visualization Research Explained.* Blog post.
- Hullman, J. (2020, April 06). [Being Bayesian with visualization](https://medium.com/multiple-views-visualization-research-explained/being-bayesian-with-visualization-669892dc024b). *Multiple Views: Visualization Research Explained.* Blog post.
- Kashnitsky, I. (2019). [Dotplot – the single most useful yet largely neglected dataviz type](https://ikashnitsky.github.io/2019/dotplot/ (Replace barplots). Blog post.
- Kirk, A. (2019, August 07). [Five ways to design for red-green colour blindness.](https://www.visualisingdata.com/2019/08/five-ways-to-design-for-red-green-colour-blindness/) Blog post.
- Leo, S. (2019, March 27). [Mistakes, we’ve drawn a few: Learning from our errors in data visualisation](https://medium.economist.com/mistakes-weve-drawn-a-few-8cdd8a42d368). *The Economist.* Online. 
- Ranzolin, D. (2019, July 07). [Thoughts on animation and movement in data visualization.](https://daranzolin.github.io/2019-07-07-animation-thoughts/) Blog post.
- Scherer, C. (2019). [The evolution of a ggplot](https://cedricscherer.netlify.com/2019/05/17/the-evolution-of-a-ggplot-ep.-1/). Blog post.
- Schwabish, J. (2018, November 19). [Teaching data visualization to kids](https://policyviz.com/2018/11/19/teaching-data-visualization-to-kids/). *PolicyViz.* Online. 
- Tol, P. (2019, May 25). [Notes on color palettes for scientific visualizations](https://personal.sron.nl/~pault/). Blog post.


<br />



## Tools

- [Coolors](https://coolors.co/): Online palette generator and explorer. Can also display created alettes under many types of colorblindness.
- [Digital Story Templates](https://github.com/ft-interactive/story-playbook): The Financial Times has created a set of six digital story templates to help its reporters and editors commission digital and visual stories.
- [NAPA Cards](http://napa-cards.net/): Narrative Patterns for Data-Driven Storytelling.
- [Neatline](https://neatline.org/): Neatline allows scholars, students, and curators to tell stories with maps, images and timelines.
- [RAW Graphs](https://rawgraphs.io/): RAW Graphs is an open source data visualization framework built with the goal of making the visual representation of complex data easy for everyone.
- [Scrollama](https://pudding.cool/process/introducing-scrollama/): Scrollama is a modern and lightweight JavaScript library for scrollytelling.
- [TinEye](https://labs.tineye.com/): TinEye is a tool that can extract color palettes from an image. It also has image search capabilities.
- [The Vistorian.](https://networkcube.github.io/vistorian/web/index.html) The Vistorian is an online platform that provides interactive visualization for various kinds of networks. It is a collaborative open-source research-project currently in the prototyping phase. It also allows you to import CSV files to visualize.
- [Who can use this?](https://whocanuse.com/?b=FFFFFF&c=663399&f=20&s=): A tool that brings attention and understanding to how color contrast can affect different people with visual impairments.


<br />

## Tutorials

- Burkhart, C. [Streetmaps: Create a streetmap of your favorite city with ggplot2 and powerpoint.](https://ggplot2tutor.com/streetmaps/streetmaps/) Blog post. Burkhart's site also includes other tutorials to help you master ggplot2. Each tutorial provides a step-by-step guide that teaches you how to create visualizations that go beyond the basics of ggplot2.

<br />


## R Packages

**Extensions**

- [brolgar](https://github.com/njtierney/brolgar): Package to **br**owse **o**ver **l**ongitudinal data **g**raphically and **a**nalytically in **R**, by providing tools to efficiently explore raw longitudinal data, calculate features (summaries) for individuals, and evaluate diagnostics of statistical models.
- [ggrough](https://xvrdm.github.io/ggrough/index.html): Package to converts ggplot2 plots to rough/sketchy charts, using the javascript `roughjs` library.
- [vtree](https://nbarrowman.github.io/vtree.html): Package for displaying nested subsets of a data frame.
- [waffle](https://github.com/hrbrmstr/waffle): Package to create waffleplots

**Palettes/Themes**

- [paletteer](https://github.com/EmilHvitfeldt/paletteer): Comprehensive collection of palettes in R. Includes palettes from many, many different R packages.
- [dutchmasters](https://github.com/EdwinTh/dutchmasters): Collection of color palettes based on paintings by the Dutch masters Johannes Vermeer and Rembrandt van Rijn.
- [harrypotter](https://github.com/aljrico/harrypotter): Collection of palettes based on the Harry Potter film series.
- [NineteenEightyR](https://github.com/m-clark/NineteenEightyR): Collection of color palettes based on the 80s.
- [tvthemes](https://github.com/Ryo-N7/tvthemes): Collection of various ggplot2 themes and color/fill palettes based on everybody’s favorite TV shows.
- [wesanderson](https://github.com/karthik/wesanderson): Collection of color palettes based on Was Anderson movies.

**Color Blindness**

- [colorblindr](https://github.com/clauswilke/colorblindr): Simulate colorblindness in production-ready R figures.

<br />


## Data for Viz

- [R4DS online learning community](https://github.com/rfordatascience): A GitHub organization for the R4DS online learning community.
- [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday): Real-world data that can be used for wrangling and visualization.
- [The Stanford Open Policing Project](https://openpolicing.stanford.edu/data/): Standardized police stop data are available to download (by location). The data are provided in both CSV and RDS formats. In addition, shapefiles are available for select locations.



<br />


## Miscellaneous

- [Flyer from Columbia Data Science Institute art contest](https://statmodeling.stat.columbia.edu/2018/09/15/columbia-data-science-institute-art-contest/) 
