---
title: "Statistics Education Research Seminar: Teaching Statistics from a Modeling Perspective"
author: "~"
date: 2018-04-06
tags: ["Teaching", "Research"]
---

My colleague Robert delMas is teaching our doctoral-level research seminar, EPsy 8271 next fall, and it looks to be an interesting topic. The details about the course follow:


## EPSY 8271 | Statistics Education Research Seminar: Teaching Statistics from a Modeling Perspective (3 credits)


**Day/Time:** Fridays, 9:00 a.m.&ndash;11:30 a.m. (Fall 2018)<br />
**Location:** 220 Wulling Hall <br />
**Instructor:** Robert delMas, Ph.D.

This seminar will focus on research related to teaching introductory statistics through a modeling approach. Students will read and discuss:

- Scholarship related to the similarities and differences between mathematical and statistical models
- Research conducted on the development of students' (and teachers') understanding of probability and statistics through modeling-based instructional approaches

During this process, students will learn about and critique research methods, critically examine research findings from studies, and consider implications for teaching.

As a capstone to the course, each student will produce a scholarly paper that explores, in more depth, a research area covered during the course.
 
For more information, contact Robert delMas, [delma001@umn.edu](mailto::delma001@umn.edu). 
