---
title: "Q&A with Becoming a Teacher of Statistics Class: Part III"
author: "~"
date: 2018-04-02
tags: ["Teaching", "FAQ"]
css: "/css/bracket.css"
---

This post is the third in a series of blogposts in which I respond to questions from the students in the *Becoming a Teacher of Statistics* course. In today's posting I respond to questions related to teaching.


#### With a flipped classroom, the professor tapes their lecture and has students view the video online. I think the logical extreme of this is that at some point, certain lectures will become immensely popular or polished to the point of surpassing local professors' lectures. Could you see the flipped classroom evolving to the point of removing the need for local professors to record themselves, given certain excellent online lectures?

Potentially. Although I hope not. In my experience, not every class emphasizes the same thing, so while there are some concepts that are consistent across courses, the "local" professors bring something unique to the class they are teaching. Maybe it is this variation that is important for the professor's to capture, rather than re-inventing the wheel of trying to give a lecture on  a common topic like OLS estimation, say. If professors could focus on how to build-on these pre-canned lectures, rather than spending time and effort re-inventing them, it seems like a better use of resources. 

To play devil's advocate for a minute, how do we know when we have hit the apex in video lectures? Is popularity a signifier of consenus of greatness? (Counterpoint: As of this writing, `@realDonaldTrump` has 49.8 million followers on Twitter.) Or is it that we come to this conclusion once a really great statistician has produced a video on a particular topic (e.g., [Hastie and Tibshirani's lectures on Machine Learning](https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about))? 

This was tried in the early 1960's for introductiry statistics, when the [Continental Classroom](https://en.wikipedia.org/wiki/Continental_Classroom) broadcast a course in probability and statistics on NBC taught by Frederick Mosteller. They also developed a textbook and other materials to accompany the course. Students received credit by enrolling in the course through a local college or university, and successfully completing the course examinations, which were mailed out to participating institutions. Aside from instant name recognition, this course was also immensely popular; more than 75,000 students took the probability and statistics course for credit at 320 colleges&mdash;which was broadcast between 6:00&ndash;7:00AM. (About 1.2 million people viewed the course but did not take it for credit.)

Sixty-plus years later, many people have probably never heard of the *Continental Classroom*, or haven't thought about it in many decades. The content (which you can view at the American Statistical Association's headquarters in Alexandria, VA) is, not surprisingly, out of date. In the Twitter age things go out of date quickly. Even when attempts to update content are made, it is still hard. There was a great series of approximately 30 videos recorded in 1989, [Against All Odds: Inside Statistics](https://www.amazon.com/Against-All-Odds-Statistics-episodes/dp/1559460911), that introduced topics in statistics. (These loosely corresponded with topics in David Moore's *Introduction to the Practice of Statistics* textbook.) By the early 2000's these seemed quite dated. Although the videos were [updated in 2013](https://www.learner.org/courses/againstallodds/unitpages/index.html), it is unclear how much the content changed. (Why are we still worrying about creating stem-and-leaf plots in 2018!??)


#### In your CATALST paper written with Huberty you mention that after school computer labs can be a potential improvement for the CSI courses you installed in Minnesota schools. Since it's been a couple years, have you seen any schools take you up on this idea? I would agree that more one-on-one time with a teacher may be more beneficial for shyer students. Especially for those in the beginning of the course that have the preconceived notion that they "suck at mathematics and therefore will not do as well as in your course".

I think many of the teachers make sure time is available after school for students to work on the computers with TinkerPlots&trade;. What I don't know is how many students take advantage of it. Many of them are involved in after-school activities, or have other obligations that keep them from making it into the lab after school. 

I think what tends to be more important than the one-on-one time is the pedagogy used in the classroom. The educational research overwhelmingly suggests that pedagogy matters for student learning, and that students in student-centered classrooms outperform their counterparts in lecture-based courses. (This is especilly true for minority and disadvantaged students; see [here](https://college.unc.edu/2014/09/02/hoganstudy/).) 


#### Do you change your material and/or approach when teaching intro stats to high schoolers (AP or College in the Schools, for example) versus teaching it to undergrads versus grad students?

Great question. Let me preface my answer with saying that although I taught high school for four years, this was around 1998 (the Backstreet Boys and N'Sync were big) and I haven't really taught that age-level since.

From working with high school teachers, and from some recollection, the big difference is that when teaching a high school class, you have far more time than we do at the university/college level. High school courses tend to meet every day, while we only meet twice a week. This means you can allow more time for the concepts and skills to develop when teaching a high school course. 

The assessments are also generally far less high-stakes than they are at the college level. In college you may have one or two exams that make up almost all of your grade. In high school, it is not uncommon to have many assessment opportunities throughout a course. 

So, material-wise, I would employ many of the same materials in the high school course that we do in the college course. But, I would supplement these with other activities and materials that build-on the ideas and give students opportunities to practice what they've learned.

Pedagogically, I would try to approach things the same way, including discussions and cooperative learning. I believe that learning takes hard work and it is the student's responsibility. I can facilitate that learning, but it is ultimately up to the student to take on that hard work. The brain is a muscle that needs to be worked out. Like physical work outs, you need to build-up to larger "weights". Focusing on the process, not the product, is also important as the goal (learning) is a long-term outcome. It may be harder to convinve a high school student that this process, which takes time, is worthwhile.


