---
title: A Couple Interesting Reads
author: Andy
date: '2022-04-27'
slug: []
categories:
  - Tech
tags:
  - Miscellaneous
  - Science
subtitle: ''
description: ''
image: ''
showtoc: false
---


Here are a couple of things that I have read that I wanted to share.

# Math Phobia: An American Crisis

The first was a short piece in the *Harvard Business Review* called [Americans Need to Get Over Their Fear of Math ](https://hbr.org/2019/10/americans-need-to-get-over-their-fear-of-math). The author, Sian Beilock, paints the thesis that math phobia is a liability for the U.S. given the importance of STEM skills and jobs to the current marketplace. Here is the quote that stood out to me:

> Finally, we need to reject the social acceptability of being bad at math. Think about it: You don’t hear highly intelligent people proclaiming that they can't read, but you do hear many of these same individuals talking about "not being a math person."

Hear, hear!


# Structured Procrastination

In the second piece called [Structured Procrastination](http://www.structuredprocrastination.com/), John Perry, argues that procrastinators can do better prioritizing important projects. He argues that while procrastinators put off things they have to do, it does not mean doing absolutely nothing. There are some gems in here:

> Procrastinators often follow exactly the wrong tack. They try to minimize their commitments, assuming that if they have only a few things to do, they will quit procrastinating and get them done. But this goes contrary to the basic nature of the procrastinator and destroys his most important source of motivation. The few tasks on his list will be by definition the most important, and the only way to avoid doing them will be to do nothing. This is a way to become a couch potato, not an effective human being.

Also,

> Tasks that seem most urgent and important are on top. But there are also worthwhile tasks to perform lower down on the list. Doing these tasks becomes a way of not doing the things higher up on the list...The trick is to pick the right sorts of projects for the top of the list. The ideal sorts of things have two characteristics, First, they seem to have clear deadlines (but really don't). Second, they seem awfully important (but really aren't). Luckily, life abounds with such tasks. In universities the vast majority of tasks fall into this category, and I'm sure the same is true for most other large institutions.


# The Devil Teaches Thermodynamics

The last piece is a short poem that was published in Roald Hoffman's book, [Chemistry Imagined: Reflections on Science](http://www.amazon.com/exec/obidos/ASIN/1560982144/braipick-20. I saw this on [The Marginalian](https://www.themarginalian.org/2019/02/26/the-devil-teaches-thermodynamics-roald-hoffmann-sean-ono-lennon/). Hoffman is a Nobel Prize winning chemist who is also a "literary artist". You can watch Sean Ono Lennon recite the poem, which he read at the second annual *Universe in Verse* celebration.


```{r echo=FALSE}
vembedr::embed_vimeo("319547709")
```




