---
title: Books I Bought
author: Andy
date: '2021-08-31'
slug: []
categories: []
tags:
  - Miscellaneous
subtitle: ''
description: ''
image: ''
showtoc: false
---

I went to the Arc today and bought several books. (It's hard to beat a price tag of 2.99!) So, in the spirit of Nick Hornby's column in the *Guardian*, I thought I would chronicle these books along with the reason I bought each.  

### BOOKS BOUGHT:

**Bruce**&mdash;*Peter Ames Carlin*: A biography of Bruce Springsteen, bought because he is The Boss.

**Going for a Beer** and **A Night at the Movies or, You Must Remember This**&mdash;*Robert Coover*: I got into Coover's work after reading a book on writing in which he was featured in a chapter. He has written some really great short stories and he also was a founder of the Electronic Literature Organization in 1999 which promotedthe publication of literature in the "new" electronic format.

**The Black Death**&mdash;*Philip Ziegler*: A book on the plague that swept through Europe in the mid 1300s wiping out one-third of the English population in three years. I have several books on pandemics; from Ebola to the flu. Maybe I will one day want to read about COVID as well.

**Roads Less Traveled: Dispatches from the Ends of the Earth**&mdash;*Catherine Watson*: Watson was the first travel editor for the Minneapolis Star Tribune (so the back cover of the book tells me). This book of travel essays I bought on a lark and am hoping her perspective as a native Minnesotan will resonate.

**Enduring Love**&mdash;*Ian McEwan*: I have most of McEwan's oevre and have loved all of them.

**The Keeper of Lost Causes**&mdash;*Jussi Adler-Olsen*: This is a detective story that I picked up because I liked the title. Plus there is a bird cage on the cover. Who doesn't want to read a book that has a bird cage on the cover. The front cover also tells me that the author won the [Glass Key Award](https://en.wikipedia.org/wiki/Glass_Key_award), so I am optimistic.

**Ojibwe Waasa Inaabida: We Look in All Directions**&mdash;*Thomas Peacock* and *Marlene Wisuri*: I have a large collection of books on the Native Americans of the plains and especially of Minnesota. Fun fact: When I was a youngster and we were asked what we wanted to be when we grew up, while most of my classmates said astronaut or baseball player, my answer was Crazy Horse.

**A Man Called Ove**&mdash;*Fredrik Backman*: This has been on my Goodreads "to-read" list for awhile. My sister tells me it is great!

**The Trial of Henry Kissinger**&mdash;*Christopher Hitchens*: Hitchens is another author I read a lot of. He was a Republican columnist that I truly respected and a brilliant debater. His feud with Gore Vidal is legendary and the shade that they dished was top-notch. I miss really, really smart people arguing the merits of a thing rather than just trying to out-shout each other.

**Leonard Cohen: Hallelujah**&mdash;*Tim Footman*: A biography of the late, great Leonard Cohen. Poet. Song writer. And a voice that gives you shivers.

**The Art Spirit**&mdash;*Robert Henri*: This is the writings that lay out the philosophy espoused by Henri on whta it means to be an artist. I feel a kindred spirit to artists, so this sounded good to me.

**Staying the Course: A Runner's Toughest Race**&mdash;*Dick Beardsley* and *Maureen Anderson*: In the 1982 Boston Marathon, Beardsley lost by 2 seconds to Alberto Salzar. This book tells that story and the aftermath of Beardsley's life (farm accident, almost overdosing, addiction) from his point of view. I read *Duel in the Sun* a year or so ago (about this race) and loved every second. I hope this will be as good.

**John Dillinger Slept Here: A Crook's Tour of Crime and Corruption in St. Paul, 1920-1936**&mdash;*Paul Maccabee*: I also have several books on crime in Minnesota. Someday I might put together a map that pins locations of interest by culling the info in these books....in all my infinite spare time.






